language: ruby
cache: bundler

rvm:
  - 2.0.0

gemfile:
    - Gemfile

script: 'bundle exec rspec'

notification:
  email:
    recipients:
      - nflood@echonet.org
    on_failure: change
    on_success: never

before_install:
  - gem install -v 1.17.3 bundler --no-rdoc -no-ri
  - bundle _1.17.3_ install

# before_install: 'rm ${BUNDLE_GEMFILE}.lock'
# before_script: 'bundle update'
