language: ruby
cache: bundler

rvm:
  - 2.0.0

gemfile:
    - Gemfile

script: 'bundle exec rspec'

notification:
  email:
    recipients:
      - nflood@echonet.org
    on_failure: change
    on_success: never

# before_install: 'rm ${BUNDLE_GEMFILE}.lock'
# before_script: 'bundle update'
