language: ruby
cache: bundler

rvm:
  - 2.0.0

script: 'rspec'

notification:
  email:
    recipients:
      - nflood@echonet.org
    on_failure: change
    on_success: never

before_install: gem install rspec
before install: gem install rack-test