AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'petit-lambda Petit URL Shortener backend for Lambda and API-Gateway

  '
Parameters:
  ServiceBaseUrl:
    Description: Please provide the base url for your URL shortener
    Type: String
    AllowedPattern: .+
  NotFoundDestination:
    Description: Please provide a location to which users will be routed if the shortcode
      does not resolve to an address.
    Type: String
    AllowedPattern: .+
  ArtifactsBucket:
    Description: You must provide the bucket name where the petit-api.yml file has
      been uploaded.
    Type: String
    AllowedPattern: .+
Resources:
  PetitDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      Tags:
      - Key: ApplicationName
        Value: Petit URL Shortener
      TableName:
        Fn::Sub: PetitVx
      AttributeDefinitions:
      - AttributeName: shortcode
        AttributeType: S
      - AttributeName: destination
        AttributeType: S
      KeySchema:
      - AttributeName: shortcode
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: destinationIndex
        KeySchema:
        - AttributeName: destination
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  PetitRedirector:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PetitRedirectorFunction
      Description: 'URL shortener function that simply redirects traffic to destinations
        stored in dynamodb. (Note: You must connect this to your load balancer manually.
        SAM does not currently provide a way for an application load balancer to be
        specified as an event source.)'
      Tags:
        ApplicationName: Petit URL Shortener
      CodeUri: s3://serverless.echocommunity.org/dd74454e40d6a46a518b55166a93f010
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 3
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: PetitDatabase
      Environment:
        Variables:
          NOT_FOUND_DESTINATION:
            Ref: NotFoundDestination
          TABLE_NAME:
            Ref: PetitDatabase
  PetitAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PetitAPIFunctionVx
      Description: URL shortener fucntion that provides an API for crud operations
      Tags:
        ApplicationName: Petit URL Shortener
      CodeUri: s3://serverless.echocommunity.org/91a6d562117f8c0e7f946cfe4e8016d9
      Handler: lambda.handler
      Runtime: ruby2.5
      Environment:
        Variables:
          DB_TABLE_NAME:
            Ref: PetitDatabase
          SERVICE_BASE_URL:
            Ref: ServiceBaseUrl
      MemorySize: 128
      Timeout: 30
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: PetitDatabase
  PetitAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: PetitAPI
      StageName: vx
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: s3://${ArtifactsBucket}/petit-api.yml
      EndpointConfiguration: EDGE
  ConfigLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - PetitAPIFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PetitAPIFunction
      Principal: apigateway.amazonaws.com
Outputs:
  APIEndpoint:
    Description: API Endpoint URL
    Value:
      Fn::Sub: https://${PetitAPI}.execute-api.${AWS::Region}.amazonaws.com/vx/
